### ISSUE TITLE
Error running scanner: KeScanner, KeVersionScanner, FirewallPolicyScanner, and IapScanner

### ISSUE THREAD

**Issue by abhishekupadhyaya** [forseti-security/forseti-security#3152]
- [x] Fix FirewallPolicyScanner
- [x] Fix IapScanner
- [x] Fix KeScanner (v2.21)
- [x] Fix KeVersionScanner (v2.21)
---

Hi,

We are using **release-2.18.0** in our production system.

We are seeing following errors as part of notification process:

- "serverMessage": "Error running scanner: KeScanner: 'Traceback (most recent call last):\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanner.py\", line 119, in run\n scanner.run()\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/ke_base_scanner.py\", line 216, in run\n ke_clusters = self._retrieve()\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/ke_base_scanner.py\", line 208, in _retrieve\n parent_type_name=ke_cluster_type_name))[0]\nIndexError: list index out of range\n'"

- "serverMessage": "Error running scanner: KeVersionScanner: 'Traceback (most recent call last):\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanner.py\", line 119, in run\n scanner.run()\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/ke_base_scanner.py\", line 216, in run\n ke_clusters = self._retrieve()\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/ke_base_scanner.py\", line 208, in _retrieve\n parent_type_name=ke_cluster_type_name))[0]\nIndexError: list index out of range\n'"

- "serverMessage": "Error running scanner: FirewallPolicyScanner: 'Traceback (most recent call last):\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanner.py\", line 119, in run\n scanner.run()\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/firewall_rules_scanner.py\", line 160, in run\n policy_data, _ = self._retrieve()\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/firewall_rules_scanner.py\", line 144, in _retrieve\n validate=True))\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/common/gcp_type/firewall_rule.py\", line 240, in from_dict\n firewall_dict, project_id=project_id, validate=validate)\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/common/gcp_type/firewall_rule.py\", line 202, in _transform\n return FirewallRule(validate=validate, **in_dict)\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/common/gcp_type/firewall_rule.py\", line 105, in __init__\n self.validate()\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/common/gcp_type/firewall_rule.py\", line 293, in validate\n self.firewall_action.validate()\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/common/gcp_type/firewall_rule.py\", line 692, in validate\n rule)\ngoogle.cloud.forseti.common.gcp_type.firewall_rule.InvalidFirewallActionError: Only \"tcp\" and \"udp\" can have ports specified: {'IPProtocol': 'sctp', 'ports': ['2905', '2910', '2920', '2930', '2940', '2950', '2960']}\n'"

- "serverMessage": "Error running scanner: IapScanner: 'Traceback (most recent call last):\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanner.py\", line 119, in run\n scanner.run()\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py\", line 682, in run\n all_violations, _ = self._find_violations(iap_data)\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py\", line 667, in _find_violations\n for (iap_resources, project_resource_counts) in iap_data:\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py\", line 632, in _retrieve\n firewall_rules = self._get_firewall_rules(parent.type_name)\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/scanner/scanners/iap_scanner.py\", line 531, in _get_firewall_rules\n json_string=firewall_rule.data))\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/common/gcp_type/firewall_rule.py\", line 221, in from_json\n json_dict, project_id=project_id, validate=True)\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/common/gcp_type/firewall_rule.py\", line 202, in _transform\n return FirewallRule(validate=validate, **in_dict)\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/common/gcp_type/firewall_rule.py\", line 105, in __init__\n self.validate()\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/common/gcp_type/firewall_rule.py\", line 293, in validate\n self.firewall_action.validate()\n File \"/usr/local/lib/python3.6/dist-packages/forseti_security-2.18.0-py3.6.egg/google/cloud/forseti/common/gcp_type/firewall_rule.py\", line 692, in validate\n rule)\ngoogle.cloud.forseti.common.gcp_type.firewall_rule.InvalidFirewallActionError: Only \"tcp\" and \"udp\" can have ports specified: {'IPProtocol': 'sctp', 'ports': ['2905', '2910', '2920', '2930', '2940', '2950', '2960']}\n'"

Could you please help in figuring this out?

Thank you,
Abhishek

**Comment by abhishekupadhyaya** [comment]
I have updated the issue with errors for `FirewallPolicyScanner` and `IapScanner`

**Comment by red2k18** [comment]
Is it possible for you to share the rules file the scanners that are not working in your environment?

**Comment by abhishekupadhyaya** [comment]
I have attached the file for all 4 rules in rules.zip.

In our environment, `{ORGANIZATION_ID1}` and `{ORGANIZATION_ID2}` are replaced with actual organization ids.


[rules.zip](https://github.com/forseti-security/forseti-security/files/3556697/rules.zip)

**Comment by red2k18** [comment]
I can meet with you tomorrow to debug. Please let me know what time works for you. Also, let me know the timezone you are in. Thanks!

**Comment by abhishekupadhyaya** [comment]
Anytime before 4:30pm EST works for me.

**Comment by red2k18** [comment]
ke scanner and ke version scanner are working as expected.

**Comment by blueandgold** [comment]
@red2k18 Can you give more details of how the `IndexError: list index out of range\n'` was resolved here?

**Comment by red2k18** [comment]
No action was taken by the Forseti team. It was reported by KeScanner and KeVersionScanner work as intended.

**Comment by dekuhn** [comment]
@red2k18 were you able to resolve the error messages reported by the customer. Based on the last comment is this issue resolved and should be closed or is there still outstanding concerns that need to be investigated.

**Comment by abhishekupadhyaya** [comment]
We are still seeing error messages for `FirewallPolicyScanner`, and `IapScanner`. We also still get error messages for `KeScanner`, `KeVersionScanner`.

Attached is screenshot of error logs for last 8 executions:
![Screen Shot 2019-09-06 at 1 33 05 PM](https://user-images.githubusercontent.com/8761854/64448348-79070900-d0ab-11e9-8db1-cdc75955610d.png)

Most recently, we got error messages for `KeScanner`, `KeVersionScanner` on Sept. 4th execution.

**Comment by gkowalski-google** [comment]
Hi @abhishekupadhyaya, I am looking into this issue now and am able to reproduce it. I will reach out to you if I need any more information, and hope to have an update or resolution soon.

**Comment by blueandgold** [comment]
@gkowalski-google thanks for pinpointing the problem!

**Comment by gkowalski-google** [comment]
@abhishekupadhyaya The fix for the KeScanner and KeVersion scanner will be included in the 2.21 release (which should be next week). Still looking into the other issues.

**Comment by abhishekupadhyaya** [comment]
@gkowalski-google thank you for the update.

**Comment by gkowalski-google** [comment]
@abhishekupadhyaya For the firewall rules issue (affecting FirewallPolicyScanner and IapScanner), how did you create these rules? I noticed that the Console does not support this scenario, but I am able to create them using the CLI. I am following up with this team to determine what is actually supported. Based on that, then I will consider updating this check in Forseti.

**Comment by gkowalski-google** [comment]
@abhishekupadhyaya The Kubernetes Scanner issues have been fixed in Forseti Release v2.21.0.

**Comment by gkowalski-google** [comment]
@abhishekupadhyaya We will be fixing the issue seen by the FirewallPolicyScanner and IapScanner in the v2.22.0 release.

**Comment by gkowalski-google** [comment]
This has been released as part of [Forseti Release v2.22.0](https://github.com/forseti-security/forseti-security/releases/tag/v2.22.0).
